### ISSUE TITLE
Remove bash script complexity

### ISSUE THREAD

**Issue by dvlex** [LinkedInLearning/hands-on-introduction-data-engineering-4395021#11]
## Issue Overview
Bash scripts complexity could be avoided

## Describe your environment
dev container

## Possible Solution
I created an Docker Image with a custom CLI interface, based on your bash scripts, to avoid certain complexity starting dev purposes airflow, I hope it could be interesting for you, and I'm open to add features and modify this Docker image

Repo: https://github.com/lexdrel/airflow-standalone-dev
Docker Hub Image: https://hub.docker.com/repository/docker/lexdrel/airflow-2.6.3-python-3.11/general

**Comment by vinooganesh** [comment]
Thanks @dvlex . I actually made the explicit decision to not use the docker version of airflow mostly because the manual install helps people understand what is actually occurring during the install process. Maybe in subsequent iterations of the course we'll have airflow deployed in docker, but for now, we'll keep it as a manual install
